routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/about', [App\Http\Controllers\AboutController::class, 'index'])->name('about');
Route::get('/services', [App\Http\Controllers\ServiceController::class, 'index'])->name('services');
Route::get('/albums-web', [App\Http\Controllers\NewsController::class, 'index'])->name('albums-web.index');
Route::get('/albums-web/{id}', [App\Http\Controllers\NewsController::class, 'show'])->name('albums-web.show');
Route::get('/contact', [App\Http\Controllers\ContactController::class, 'index'])->name('contact');
Route::get('/privacy-policy', [App\Http\Controllers\HomeController::class, 'privacyPolicy'])->name('privacy-policy');

Route::get('/register-verification', [App\Http\Controllers\AccountVerificationController::class,'registerVerification'])->name('register-verification.index');

Route::group(
    ['prefix' => 'portal'],
    function () {
        Route::get('dashboard', [App\Http\Controllers\DashboardController::class,'index'])->name('portal.index');
        Route::resource('profiling', App\Http\Controllers\StudentProfileController::class);

        Route::resource('account-verification', App\Http\Controllers\AccountVerificationController::class);

        Route::get('account-verification/{id}/verify/{status}', [App\Http\Controllers\AccountVerificationController::class, 'verifyModal'])->name('account-verification.verify-modal');

        Route::put('account-verification/{id}/verify/{status}', [App\Http\Controllers\AccountVerificationController::class, 'verify'])->name('account-verification.verify');

        Route::get(
            'student-profile-list',
            [App\Http\Controllers\StudentProfileController::class,
            'studentProfileDataTable']
        )->name('student-profile-list');

        Route::get(
            '/profiling/delete/{id}',
            [App\Http\Controllers\StudentProfileController::class,'delete']
        )->name('profiling.delete');

        Route::get(
            '/profiling/image/{file}',
            [App\Http\Controllers\StudentProfileController::class, 'getImage']
        )->name('profiling.image');

        Route::resource('visitor-log', App\Http\Controllers\VisitorLogController::class);

        Route::get(
            'visitor-log-list',
            [App\Http\Controllers\VisitorLogController::class,
            'visitorLogDatatable']
        )->name('visitor-log-list');

        Route::get(
            '/visitor-log/delete/{id}',
            [App\Http\Controllers\VisitorLogController::class,'delete']
        )->name('visitor-log.delete');

        Route::resource('file-doc', App\Http\Controllers\FileDocController::class);

        Route::get(
            'file-doc-list',
            [App\Http\Controllers\FileDocController::class,
            'fileDocDatatable']
        )->name('file-doc-list');

        Route::get(
            '/file-doc/delete/{id}',
            [App\Http\Controllers\FileDocController::class,'delete']
        )->name('file-doc.delete');

        Route::get(
            '/download-docs/{id}',
            [App\Http\Controllers\FileDocController::class, 'downloadDocs'],
        )->name('download.docs');

        Route::resource('seminar', App\Http\Controllers\SeminarController::class);

        Route::get(
            'seminar-list',
            [App\Http\Controllers\SeminarController::class,
            'seminarDatatable']
        )->name('seminar-list');

        Route::get(
            '/seminar/delete/{id}',
            [App\Http\Controllers\SeminarController::class,'delete']
        )->name('seminar.delete');

        Route::get(
            '/seminar/register/{id}',
            [App\Http\Controllers\SeminarController::class,'register']
        )->name('seminar.register');

        Route::post(
            '/seminar/join/{id}',
            [App\Http\Controllers\SeminarController::class,'join']
        )->name('seminar.join');

        Route::get(
            'seminar/{id}/attendance',
            [App\Http\Controllers\SeminarAttendanceController::class,'create']
        )->name('seminar.attendance.create');

        Route::post(
            'seminar/{id}/attendance/user',
            [App\Http\Controllers\SeminarAttendanceController::class,'attend']
        )->name('user.attend.seminar');

        Route::post(
            'seminar/{id}/attendance',
            [App\Http\Controllers\SeminarAttendanceController::class,'store']
        )->name('seminar.attendance.store');

        Route::resource('evaluation', App\Http\Controllers\StudentEvaluationController::class);

        Route::get(
            'seminar/{id}/evaluation',
            [App\Http\Controllers\StudentEvaluationController::class,'create']
        )->name('seminar.evaluation.create');

        Route::post(
            'seminar/{id}/evaluation',
            [App\Http\Controllers\StudentEvaluationController::class,'store']
        )->name('seminar.evaluation.store');

        Route::get(
            'evaluation-list',
            [App\Http\Controllers\StudentEvaluationController::class,
            'evaluationDatatable']
        )->name('evaluation-list');

        Route::resource('counseling', App\Http\Controllers\CounselingController::class);

        Route::get(
            'counseling-list',
            [App\Http\Controllers\CounselingController::class,
            'individualCounselingDatatable']
        )->name('counseling-list');

        Route::get(
            '/counseling/delete/{id}',
            [App\Http\Controllers\CounselingController::class,'delete']
        )->name('counseling.delete');

        Route::resource('mini-library', App\Http\Controllers\MiniLibraryController::class);

        Route::get(
            'mini-library-list',
            [App\Http\Controllers\MiniLibraryController::class,
            'miniLibraryDatatable']
        )->name('mini-library-list');

        Route::get(
            '/mini-library/delete/{id}',
            [App\Http\Controllers\MiniLibraryController::class,'delete']
        )->name('mini-library.delete');

        Route::post('mini-library/{id}/borrower', [App\Http\Controllers\MiniLibraryItemController::class,
        'store'])->name('borrower-book.store');

        Route::get('mini-library/{id}/borrower', [App\Http\Controllers\MiniLibraryItemController::class,
        'create'])->name('borrower-book.create');

        Route::get(
            'books-borrow-list',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'borroBooksDatatable']
        )->name('books-borrow-list');

        Route::get(
            'books/borrow/{id}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'show']
        )->name('books-borrow.show');

        Route::put(
            'books/borrow/{id}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'update']
        )->name('books-borrow.update');

        Route::get(
            'borrow/request/{id}/status/{status}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'statusUpdate']
        )->name('borrow.approval');

        Route::put(
            'borrow_book/{id}/status/{status}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'borrowApproved']
        )->name('borrow_update.approval');

        Route::get(
            'borrow_book/{id}/return',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'returnBookView']
        )->name('borrow_update.return_view');

        Route::put(
            'borrow_book/{id}/return',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'returnBook']
        )->name('borrow_update.return');

        Route::resource('albums', App\Http\Controllers\AlbumController::class);

        Route::get(
            'album-list',
            [App\Http\Controllers\AlbumController::class,
            'albumDatatable']
        )->name('album-list');

        Route::get(
            '/album/delete/{id}',
            [App\Http\Controllers\AlbumController::class,'delete']
        )->name('albums.delete');

        Route::post(
            'albums-items/{id}',
            [App\Http\Controllers\AlbumController::class,'addPhotoAlbum']
        )->name('album-items.store');

        Route::resource('general-settings', App\Http\Controllers\GeneralController::class);

        Route::resource('counseling-request', App\Http\Controllers\CounselingRequestController::class);

        Route::get(
            'counseling-request-list',
            [App\Http\Controllers\CounselingRequestController::class,
            'counselingRequestDatatable']
        )->name('counseling-request-list');

        Route::get(
            'request/{id}/status/{status}',
            [App\Http\Controllers\CounselingRequestController::class,
            'statusUpdate']
        )->name('request.approval');

        Route::put(
            'request/{id}/status/{status}',
            [App\Http\Controllers\CounselingRequestController::class,
            'updateCounseling']
        )->name('request.update');

        Route::put('notification/{id}', [App\Http\Controllers\NotificationController::class, 'markAsViewNotification'])->name('markAsView');

        Route::get(
            'notification/all',
            [App\Http\Controllers\NotificationController::class,
            'index']
        )->name('notifications.index');
    }
);

resources/views/portal/logs/create.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Gender and Development | Portal</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript" src="{{asset('js/all.js')}}"></script>
    
    <!-- plugins:js -->
    
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{{ asset('web-design-portal/vendors/chart.js/Chart.min.js') }}"></script>
    <script src="{{ asset('web-design-portal/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('web-design-portal/vendors/progressbar.js/progressbar.min.js') }}"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{{ asset('web-design-portal/js/off-canvas.js') }}"></script>
    <script src="{{ asset('web-design-portal/js/hoverable-collapse.js') }}"></script>
    <script src="{{ asset('web-design-portal/js/template.js') }}"></script>
    <script src="{{ asset('web-design-portal/js/settings.js') }}"></script>
    <script src="{{ asset('web-design-portal/js/todolist.js') }}"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <!-- <script src="{{ asset('web-design-portal/js/dashboard.js') }}"></script> -->
    <script src="{{ asset('web-design-portal/js/Chart.roundedBarCharts.js') }}"></script>
    <!-- End custom js for this page-->

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/all.css') }}" >

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/feather/feather.css') }}">
    <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/mdi/css/materialdesignicons.min.css') }}">
    <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/ti-icons/css/themify-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/typicons/typicons.css') }}">
    <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/simple-line-icons/css/simple-line-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/css/vendor.bundle.base.css') }}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- <link rel="stylesheet" href="{{ asset('web-design-portal/vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
    <link rel="stylesheet" href="{{ asset('web-design-portal/js/select.dataTables.min.css') }}"> -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ asset('web-design-portal/css/vertical-layout-light/style.css') }}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{{ asset('web-design-portal/images/favicon.png') }}" />
</head>
<body>
    <!-- WRAPPER -->
	<div id="app">
        <div class="content-wrapper">
            <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <div align='right' style="margin-bottom: 20px;">
                            <a href="{{ route('visitor-log.index') }}"><button type="button" class="btn btn-default"><i class="fas fa-chevron-left"></i> Back</button></a>
                        </div>
                        <h4 class="card-title">Visitors Log</h4>
                        <div class="alert alert-info" role="alert">
                            Select Student if you have recurring data if not, fill name and section.
                        </div>
                        <div class="col-md-12">
                            <div class="table-responsive">
                            <table class="table" id="bhw-table">
                                <thead>
                                    <tr align="center">
                                        <th width="15%" style="text-align:center" >Select Student</th>
                                        <th width="20%" style="text-align:center" >Name</th>
                                        <th width="15%" style="text-align:center" >Section</th>
                                        <th width="10%" style="text-align:center" >Date of Visit</th>
                                        <!-- <th width="20%" style="text-align:center" >Remarks</th> -->
                                        <th width="20%" style="text-align:center" >Reason of Visit</th>
                                        <th width="15%" style="text-align:center" >Action</th>
                                    </tr>
                                </thead>
                                <tbody id="table_logs">
                                    @php for($i = 0; $i < 5; $i++) { @endphp
                                    <tr align="center">
                                        <td>
                                            <select data-live-search="true" id="selectpick{{$i}}" title="Choose Student..." class="form-control select-picker" name="select_student{{$i}}">
                                                    <option value="">Create New</option>
                                                @foreach($students as $student)
                                                    <option value="{{ $student->id }}" data-subtext="{{ $student->section }}">{{ $student->first_name . ' ' .$student->last_name }}</option>
                                                @endforeach
                                            </select>
                                        </td>
                                        <td><input type="text" class="form-control" name="name" id="name{{$i}}" ></td>
                                        <td><input type="text" class="form-control" name="section" id="section{{$i}}" ></td>
                                        <td><input type="datetime-local" class="form-control" name="date_visit" id="date_visit{{$i}}"></td>
                                        <td><textarea name="reasons" id="reason{{$i}}" class="form-control" ></textarea></td>
                                        <td><button class="btn btn-primary" id="save{{$i}}" onclick="addLogs({{$i}})">Save</button></td>
                                    </tr>
                                    @php } @endphp
                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-7" align="left">
                                    <button class="btn btn-primary addNew" type="button" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false" ><i class="fa fa-plus-square" aria-hidden="true"></i> ADD ROW</button>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
<script src="{{ asset('web-design-portal/vendors/js/vendor.bundle.base.js') }}"></script>
<script>
    $('.select-picker').selectpicker();
    $('.name_new').hide();

    $('#selectpick0').change(function () {
        var pick = $('#selectpick0').find(":selected").val();
        if(pick != '') {
            $('#name0').prop("disabled", true );
            $('#section0').prop("disabled", true );
        } else {
            $('#name0').prop("disabled", false );
            $('#section0').prop("disabled", false );
        }
    });

    $('#selectpick1').change(function () {
        var pick = $('#selectpick1').find(":selected").val();
        if(pick != '') {
            $('#name1').prop("disabled", true );
            $('#section1').prop("disabled", true );
        } else {
            $('#name1').prop("disabled", false );
            $('#section1').prop("disabled", false );
        }
    });

    $('#selectpick2').change(function () {
        var pick = $('#selectpick2').find(":selected").val();
        if(pick != '') {
            $('#name2').prop("disabled", true );
            $('#section2').prop("disabled", true );
        } else {
            $('#name2').prop("disabled", false );
            $('#section2').prop("disabled", false );
        }
    });

    $('#selectpick3').change(function () {
        var pick = $('#selectpick3').find(":selected").val();
        if(pick != '') {
            $('#name3').prop("disabled", true );
            $('#section3').prop("disabled", true );
        } else {
            $('#name3').prop("disabled", false );
            $('#section3').prop("disabled", false );
        }
    });

    $('#selectpick4').change(function () {
        var pick = $('#selectpick4').find(":selected").val();
        if(pick != '') {
            $('#name4').prop("disabled", true );
            $('#section4').prop("disabled", true );
        } else {
            $('#name4').prop("disabled", false );
            $('#section4').prop("disabled", false );
        }
    });

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    function addLogs(rows) {
        $.ajax({
            type: "POST",
            url: "{{route('visitor-log.store')}}",
            data: {
                row: rows,
                name: $('#name'+rows).val(),
                student_id: $('#selectpick'+rows).find(":selected").val(),
                section: $("#section"+rows).val(),
                date_visit: $('#date_visit'+rows).val(),
                reason: $('#reason'+rows).val()
            },
            dataType: "json",
        }).done(function (data) {
                toastMessage('Success',data.desc,data.status);
                $('#save'+rows).prop("disabled", true );
                $('#name'+rows).prop("disabled", true );
                $('#selectpick'+rows).prop("disabled", true );
                $('#section'+rows).prop("disabled", true );
                $('#date_visit'+rows).prop("disabled", true );
                $('#reason'+rows).prop("disabled", true );
        });
    }

    var countItem = 4;
    $(".addNew").click(function(e){
        e.preventDefault();
        countItem ++;
        $('#table_logs').append('<tr align="center" class="appendRow">'+
            '<tr align="center">'+
                '<td><select data-live-search="true" id="selectpick'+countItem+'" title="Choose Student..." class="form-control select-picker'+countItem+'" name="select_student'+countItem+'">'+
                    '<option value="">Create New</option>'+
                    @foreach($students as $student)
                        '<option value="{{ $student->id }}" data-subtext="{{ $student->section }}">{{ $student->first_name . ' ' .$student->last_name }}</option>'+
                    @endforeach
                '</select></td>'+
                '<td><input type="text" class="form-control" placeholder="" name="name" id="name'+countItem+'"></td>'+
                '<td><input type="text" class="form-control" name="section" id="section'+countItem+'"></td>'+
                '<td><input type="datetime-local" class="form-control" name="date_visit" id="date_visit'+countItem+'"></td>'+
                '<td><textarea name="reason'+countItem+'" id="reason'+countItem+'" class="form-control" ></textarea></td>'+
                '<td><button class="btn btn-primary" id="save'+countItem+'" onclick="addLogs('+countItem+')">Save</button></td>'+
            '</tr>');

        $('.select-picker'+countItem).selectpicker();

        $('#selectpick'+countItem).change(function () {
            var id = '#selectpick'+countItem;
            
            var pick = $(id).find(":selected").val();
           
            if(pick != '') {
                $('#name'+countItem).prop("disabled", true );
                $('#section'+countItem).prop("disabled", true );
            } else {
                $('#name'+countItem).prop("disabled", false );
                $('#section'+countItem).prop("disabled", false );
            }
        });

        
    })
</script>

</html>

resources/views/portal/logs/delete.blade.php
<form method="POST" id="remove_bhw_form"  class="form-horizontal" action="{{route('visitor-log.destroy',$log->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{$log->date_visit }}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{ route('visitor-log.show', $log->id) }}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/portal/logs/index.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
            <div class="card-body">
                    <div align='right'>
                        <a href="{{ route('visitor-log.create') }}" target="_blank"><button type="button" class="btn btn-primary"><i class="fas fa-plus"></i> New</button></a>
                    </div>
                <h4 class="card-title">Visitor's Logs</h4>
                <p class="card-description">
                Visitor's Log List
                </p>
                <div class="table-responsive">
                <table class="table table-striped" id="logs-table">
                    <thead>
                        <tr>
                            <th scope="col" width="10%">Image</th>
                            <th scope="col" width="20%">Name</th>
                            <th scope="col" width="10%">Date Visit</th>
                            <th scope="col" width="30%">Remarks</th>
                            <th scope="col" width="30%">Reason of Visit</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $(function() {
        $('#logs-table').DataTable(
            {
                responsive: true,
                pagingType: "full_numbers",
                processing: true,
                serverSide: true,
                type: "GET",
                ajax:"{!! route('visitor-log-list') !!}",
                columns:[
                    {data: "image","name":"image",orderable:false,searchable:false,"width":"10%", className:"v-align text-center",
                    "render": function (data) {
                        return "<center><div><img src='" + data + "' alt='Image' height='50' width='50' class='rounded-circle'></div></center>"; 
                    }},
                    {data: "full_name","name":"full_name","width":"30%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("visitor-log.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                    }},
                    {data: "date_visit", 'name' :"date_visit",orderable:false,searchable:false,"width":"10%"},
                    {data: "remarks","name":"remarks",orderable:false,searchable:false,"width":"30%"},
                    {data: "reason", 'name' :"reason",orderable:false,searchable:false,"width":"30%"}
                ]
            }
        );
    });
</script>
@endpush
@endsection

resources/views/portal/logs/show.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
            <div class="card-body">
                <div align='right'>
                <a href="{{ route('visitor-log.delete', $log->id) }}" style="color: red;" title="Delete Log Record" class="popup_form" data-toggle="modal"><i class="fa fa-trash"></i></a>
                    <a href="{{ route('visitor-log.index') }}"><button type="button" class="btn btn-default"><i class="fas fa-chevron-left"></i> Back</button></a>
                </div>
                <h4 class="card-title">{{ date('F d, Y H:i a', strtotime($log->date_visit)) }}</h4>
                <p class="card-description">
                    Basic Information
                </p>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Full name</b></label><br>
                        <p>&nbsp;{{ $log->student->first_name . ' ' . $log->student->last_name  }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        <label><b>Section</b></label><br>
                        <p>&nbsp;{{ $log->student->section }}</p>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><b>Date Visit</b></label><br>
                        <p>&nbsp;{{ date('Y-m-d H:i a', strtotime($log->date_visit)) }}</p>
                    </div>
                    <div class="form-group col-md-6">
                        <label><b>Reason</b></label><br>
                        <p>&nbsp;{{ $log->reason }}</p>
                    </div>
                </div>
                <hr>
            </div>
            </div>
        </div>
    </div>
</div>
@endsection