routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/about', [App\Http\Controllers\AboutController::class, 'index'])->name('about');
Route::get('/services', [App\Http\Controllers\ServiceController::class, 'index'])->name('services');
Route::get('/albums-web', [App\Http\Controllers\NewsController::class, 'index'])->name('albums-web.index');
Route::get('/albums-web/{id}', [App\Http\Controllers\NewsController::class, 'show'])->name('albums-web.show');
Route::get('/contact', [App\Http\Controllers\ContactController::class, 'index'])->name('contact');
Route::get('/privacy-policy', [App\Http\Controllers\HomeController::class, 'privacyPolicy'])->name('privacy-policy');

Route::get('/register-verification', [App\Http\Controllers\AccountVerificationController::class,'registerVerification'])->name('register-verification.index');

Route::group(
    ['prefix' => 'portal'],
    function () {
        Route::get('dashboard', [App\Http\Controllers\DashboardController::class,'index'])->name('portal.index');
        Route::resource('profiling', App\Http\Controllers\StudentProfileController::class);

        Route::resource('account-verification', App\Http\Controllers\AccountVerificationController::class);

        Route::get('account-verification/{id}/verify/{status}', [App\Http\Controllers\AccountVerificationController::class, 'verifyModal'])->name('account-verification.verify-modal');

        Route::put('account-verification/{id}/verify/{status}', [App\Http\Controllers\AccountVerificationController::class, 'verify'])->name('account-verification.verify');

        Route::get(
            'student-profile-list',
            [App\Http\Controllers\StudentProfileController::class,
            'studentProfileDataTable']
        )->name('student-profile-list');

        Route::get(
            '/profiling/delete/{id}',
            [App\Http\Controllers\StudentProfileController::class,'delete']
        )->name('profiling.delete');

        Route::get(
            '/profiling/image/{file}',
            [App\Http\Controllers\StudentProfileController::class, 'getImage']
        )->name('profiling.image');

        Route::resource('visitor-log', App\Http\Controllers\VisitorLogController::class);

        Route::get(
            'visitor-log-list',
            [App\Http\Controllers\VisitorLogController::class,
            'visitorLogDatatable']
        )->name('visitor-log-list');

        Route::get(
            '/visitor-log/delete/{id}',
            [App\Http\Controllers\VisitorLogController::class,'delete']
        )->name('visitor-log.delete');

        Route::resource('file-doc', App\Http\Controllers\FileDocController::class);

        Route::get(
            'file-doc-list',
            [App\Http\Controllers\FileDocController::class,
            'fileDocDatatable']
        )->name('file-doc-list');

        Route::get(
            '/file-doc/delete/{id}',
            [App\Http\Controllers\FileDocController::class,'delete']
        )->name('file-doc.delete');

        Route::get(
            '/download-docs/{id}',
            [App\Http\Controllers\FileDocController::class, 'downloadDocs'],
        )->name('download.docs');

        Route::resource('seminar', App\Http\Controllers\SeminarController::class);

        Route::get(
            'seminar-list',
            [App\Http\Controllers\SeminarController::class,
            'seminarDatatable']
        )->name('seminar-list');

        Route::get(
            '/seminar/delete/{id}',
            [App\Http\Controllers\SeminarController::class,'delete']
        )->name('seminar.delete');

        Route::get(
            '/seminar/register/{id}',
            [App\Http\Controllers\SeminarController::class,'register']
        )->name('seminar.register');

        Route::post(
            '/seminar/join/{id}',
            [App\Http\Controllers\SeminarController::class,'join']
        )->name('seminar.join');

        Route::get(
            'seminar/{id}/attendance',
            [App\Http\Controllers\SeminarAttendanceController::class,'create']
        )->name('seminar.attendance.create');

        Route::post(
            'seminar/{id}/attendance/user',
            [App\Http\Controllers\SeminarAttendanceController::class,'attend']
        )->name('user.attend.seminar');

        Route::post(
            'seminar/{id}/attendance',
            [App\Http\Controllers\SeminarAttendanceController::class,'store']
        )->name('seminar.attendance.store');

        Route::resource('evaluation', App\Http\Controllers\StudentEvaluationController::class);

        Route::get(
            'seminar/{id}/evaluation',
            [App\Http\Controllers\StudentEvaluationController::class,'create']
        )->name('seminar.evaluation.create');

        Route::post(
            'seminar/{id}/evaluation',
            [App\Http\Controllers\StudentEvaluationController::class,'store']
        )->name('seminar.evaluation.store');

        Route::get(
            'evaluation-list',
            [App\Http\Controllers\StudentEvaluationController::class,
            'evaluationDatatable']
        )->name('evaluation-list');

        Route::resource('counseling', App\Http\Controllers\CounselingController::class);

        Route::get(
            'counseling-list',
            [App\Http\Controllers\CounselingController::class,
            'individualCounselingDatatable']
        )->name('counseling-list');

        Route::get(
            '/counseling/delete/{id}',
            [App\Http\Controllers\CounselingController::class,'delete']
        )->name('counseling.delete');

        Route::resource('mini-library', App\Http\Controllers\MiniLibraryController::class);

        Route::get(
            'mini-library-list',
            [App\Http\Controllers\MiniLibraryController::class,
            'miniLibraryDatatable']
        )->name('mini-library-list');

        Route::get(
            '/mini-library/delete/{id}',
            [App\Http\Controllers\MiniLibraryController::class,'delete']
        )->name('mini-library.delete');

        Route::post('mini-library/{id}/borrower', [App\Http\Controllers\MiniLibraryItemController::class,
        'store'])->name('borrower-book.store');

        Route::get('mini-library/{id}/borrower', [App\Http\Controllers\MiniLibraryItemController::class,
        'create'])->name('borrower-book.create');

        Route::get(
            'books-borrow-list',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'borroBooksDatatable']
        )->name('books-borrow-list');

        Route::get(
            'books/borrow/{id}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'show']
        )->name('books-borrow.show');

        Route::put(
            'books/borrow/{id}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'update']
        )->name('books-borrow.update');

        Route::get(
            'borrow/request/{id}/status/{status}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'statusUpdate']
        )->name('borrow.approval');

        Route::put(
            'borrow_book/{id}/status/{status}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'borrowApproved']
        )->name('borrow_update.approval');

        Route::get(
            'borrow_book/{id}/return',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'returnBookView']
        )->name('borrow_update.return_view');

        Route::put(
            'borrow_book/{id}/return',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'returnBook']
        )->name('borrow_update.return');

        Route::resource('albums', App\Http\Controllers\AlbumController::class);

        Route::get(
            'album-list',
            [App\Http\Controllers\AlbumController::class,
            'albumDatatable']
        )->name('album-list');

        Route::get(
            '/album/delete/{id}',
            [App\Http\Controllers\AlbumController::class,'delete']
        )->name('albums.delete');

        Route::post(
            'albums-items/{id}',
            [App\Http\Controllers\AlbumController::class,'addPhotoAlbum']
        )->name('album-items.store');

        Route::resource('general-settings', App\Http\Controllers\GeneralController::class);

        Route::resource('counseling-request', App\Http\Controllers\CounselingRequestController::class);

        Route::get(
            'counseling-request-list',
            [App\Http\Controllers\CounselingRequestController::class,
            'counselingRequestDatatable']
        )->name('counseling-request-list');

        Route::get(
            'request/{id}/status/{status}',
            [App\Http\Controllers\CounselingRequestController::class,
            'statusUpdate']
        )->name('request.approval');

        Route::put(
            'request/{id}/status/{status}',
            [App\Http\Controllers\CounselingRequestController::class,
            'updateCounseling']
        )->name('request.update');

        Route::put('notification/{id}', [App\Http\Controllers\NotificationController::class, 'markAsViewNotification'])->name('markAsView');

        Route::get(
            'notification/all',
            [App\Http\Controllers\NotificationController::class,
            'index']
        )->name('notifications.index');
    }
);

app/Models/MiniLibrary.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class MiniLibrary extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * @var string
     */
    protected $table = 'mini_libraries';

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @return HasMany
     */
    public function items(): HasMany
    {
        return $this->hasMany(MiniLibraryItem::class, 'mini_library_id');
    }
}

app/Http/Controllers/MiniLibraryController.php
<?php

namespace App\Http\Controllers;

use App\Models\MiniLibrary;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class MiniLibraryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('portal.mini-library.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mini_library = MiniLibrary::count();

        return view('portal.mini-library.create', [
            'book_no' => str_pad($mini_library + 1, 8, '0', STR_PAD_LEFT)
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $mini_library = MiniLibrary::create([
            'book_no' => $request->book_no,
            'title' => $request->title,
            'description' => $request->description,
            'no_of_copies' => $request->no_of_copies,
            'author' => $request->author,
            'date_publication' => $request->date_publication,
            'publishing_company' => $request->publishing_company
        ]);

        return array(
            "status" => "success",
            'data' => $mini_library,
            'book_count' => str_pad(MiniLibrary::count() + 1, 8, '0', STR_PAD_LEFT),
            'desc' => 'Mini Library Successfully Created!'
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mini_library = MiniLibrary::findOrFail($id);

        $no_borrow = $mini_library->items()->whereNull('return_date')->value('no_of_copies');
        if ($no_borrow == null) {
            $no_borrow = 0;
        }

        $arr = [];
        if (( $mini_library->no_of_copies - $no_borrow) == 0) {
            foreach ($mini_library->items()->get() as $key => $value) {
                $arr[] = $value->due_date;
            }
        }


        return view('portal.mini-library.show', [
            'mini_library' => $mini_library,
            'no_borrow' => $no_borrow,
            'date_available' => $arr

        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mini_library = MiniLibrary::findOrFail($id);

        return view('portal.mini-library.edit', [
            'mini_library' => $mini_library
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $mini_library = MiniLibrary::findOrFail($id);

        $mini_library->update([
            'book_no' => $request->book_no,
            'title' => $request->title,
            'description' => $request->description,
            'no_of_copies' => $request->no_of_copies,
            'author' => $request->author,
            'date_publication' => $request->date_publication,
            'publishing_company' => $request->publishing_company
        ]);

        return array(
            "status" => "success",
            'data' => $mini_library,
            'desc' => 'Book Successfully Updated!'
        );
    }

    /**
     * delete
     *
     * @param int $id
     *
     * @return void
     */
    public function delete($id)
    {
        $mini_library = MiniLibrary::findOrFail($id);

        return view(
            'portal.mini-library.delete',
            ['mini_library' => $mini_library]
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mini_library = MiniLibrary::findOrFail($id);

        $mini_library->delete();

        return redirect(route('mini-library.index'));
    }

    /**
     * datatables
     *
     * @return void
     */
    public function miniLibraryDatatable()
    {
        $mini_library = MiniLibrary::all();

        $dt = DataTables::of($mini_library)
        ->addColumn('id', function ($model) {
            return $model->id;
        })
        ->addColumn('book_no', function ($model) {
            return $model->book_no;
        })
        ->addColumn('title', function ($model) {
            return $model->title;
        })
        ->addColumn('description', function ($model) {
            return $model->description;
        })
        ->addColumn('no_of_copies', function ($model) {
            return $model->no_of_copies;
        })
        ->addColumn('date_publication', function ($model) {
            return $model->date_publication == null ? '-' : date('F d, Y', strtotime($model->date_publication));
        })
        ->make(true);

        return $dt;
    }
}

resources/views/portal/mini-library/create.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div align='right' style="margin-bottom: 20px;">
                    <a href="{{ route('mini-library.index') }}"><button type="button" class="btn btn-default"><i class="fas fa-chevron-left"></i> Back</button></a>
                </div>
                <h4 class="card-title">Create Books</h4>
                <form method="POST" class="book_create" id ="book-create" action="{{ route('mini-library.store') }}">
                @csrf
                <div class="errors"></div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Book No.</label>
                        <div class="col-sm-9">
                        <input type="text" id="book_no" class="form-control" readonly="" style="border-left: solid 2.0px #ec0000" name="book_no" value="{{ $book_no }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Title</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="title" value="" style="border-left: solid 2.0px #ec0000" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">No of Copies</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="no_of_copies" value="" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Date of Publication</label>
                        <div class="col-sm-9">
                        <input type="date" class="form-control" style="border-left: solid 2.0px #ec0000" name="date_publication" value="" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Author</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="author" value="" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Publishing Company</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="publishing_company" value=""/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Description</label>
                        <div class="col-sm-9">
                            <textarea name="description" style="border-left: solid 2.0px #ec0000" data-validation="required" id="" class="form-control">

                            </textarea>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    
                    </div>
                </div>
                <div align="right" style="margin-bottom: 20px;">
                        <button type="submit" id="submit_product" class="btn btn-primary"><i class="fa fa-save" ></i> Submit</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $('#book-create').register_fields('.errors');
</script>
@endpush
@endsection

resources/views/portal/mini-library/delete.blade.php
<form method="POST" id="remove_bhw_form"  class="form-horizontal" action="{{route('mini-library.destroy',$mini_library->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{$mini_library->book_no}}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{ route('mini-library.show', $mini_library->id) }}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/portal/mini-library/edit.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div align='right' style="margin-bottom: 20px;">
                    <a href="{{ route('mini-library.index') }}"><button type="button" class="btn btn-default"><i class="fas fa-chevron-left"></i> Back</button></a>
                </div>
                <h4 class="card-title">Create Books</h4>
                <form method="POST" class="book_create" id ="book-create" action="{{ route('mini-library.update', $mini_library->id) }}">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <div class="errors"></div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Book No.</label>
                        <div class="col-sm-9">
                        <input type="text" id="book_no" class="form-control" readonly="" style="border-left: solid 2.0px #ec0000" name="book_no" value="{{ $mini_library->book_no }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Title</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="title" value="{{ $mini_library->title }}" style="border-left: solid 2.0px #ec0000" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">No of Copies</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="no_of_copies" value="{{ $mini_library->no_of_copies }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Date of Publication</label>
                        <div class="col-sm-9">
                        <input type="date" class="form-control" style="border-left: solid 2.0px #ec0000" name="date_publication" value="{{ $mini_library->date_publication }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Author</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="author" value="{{ $mini_library->author }}" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Publishing Company</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="publishing_company" value="{{ $mini_library->publishing_company }}"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Description</label>
                        <div class="col-sm-9">
                            <textarea name="description" style="border-left: solid 2.0px #ec0000" data-validation="required" id="" class="form-control">{{ $mini_library->description }}</textarea>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    
                    </div>
                </div>
                <div align="right" style="margin-bottom: 20px;">
                        <button type="submit" id="submit_product" class="btn btn-primary"><i class="fa fa-save" ></i> Submit</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $('#book-create').register_fields('.errors');
</script>
@endpush
@endsection

resources/views/portal/mini-library/index.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mini Libraries</h4>
                <p class="card-description">
                Mini Library for GAD.
                </p>
                <div class="col-md-12">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="books-tab" data-toggle="tab" href="#books" role="tab" aria-controls="books" aria-selected="true">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="borrower-tab" data-toggle="tab" href="#borrower" role="tab" aria-controls="borrower" aria-selected="true">
                            @if (Auth::user()->profile_type == 'App\\Models\\AdminProfile')
                                Borrowers
                            @else
                                Books Borrowed
                            @endIf
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <div class="tab-content profile-tab" id="myTabContent">
                        <div class="tab-pane fade show active" id="books" role="tabpanel" aria-labelledby="books-tab">
                            @if (Auth::user()->profile_type == 'App\\Models\\AdminProfile')
                            <div align='right' style="margin-bottom: 10px;">
                                <a href="{{ route('mini-library.create') }}"><button type="button" class="btn btn-primary"><i class="fas fa-plus"></i> New</button></a>
                            </div>
                            @endIf
                            <div class="table-responsive">
                            <table class="table table-striped" id="library-table">
                                <thead>
                                    <tr>
                                        <th scope="col" width="20%">Title</th>
                                        <th scope="col" width="20%">Book No.</th>
                                        <th scope="col" width="20%">Description</th>
                                        <th scope="col" width="20%">No of Copies</th>
                                        <th scope="col" width="20%">Date of Publication</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="borrower" role="tabpanel" aria-labelledby="borrower-tab">
                            @include('portal.mini-library.borrowers.index')
                        </div>
                    </div>
                </div>
                
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $(function() {
        $('#library-table').DataTable(
            {
                responsive: true,
                pagingType: "full_numbers",
                processing: true,
                serverSide: true,
                type: "GET",
                ajax:"{!! route('mini-library-list') !!}",
                columns:[
                    {data: "title","name":"title","width":"20%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("mini-library.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                    }},
                    {data: "book_no", 'name' :"book_no",orderable:true,searchable:false,"width":"20%"},
                    {data: "description", 'name' :"description",orderable:false,searchable:false,"width":"20%"},
                    {data: "no_of_copies", 'name' :"no_of_copies",orderable:true,searchable:false,"width":"20%"},
                    {data: "date_publication", 'name' :"date_publication",orderable:false,searchable:false,"width":"20%"}
                ]
            }
        );
    });
</script>
@endpush
<style>
    .table th, .table td { max-width: 200px; min-width: 70px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
</style>
@endsection