routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/about', [App\Http\Controllers\AboutController::class, 'index'])->name('about');
Route::get('/services', [App\Http\Controllers\ServiceController::class, 'index'])->name('services');
Route::get('/albums-web', [App\Http\Controllers\NewsController::class, 'index'])->name('albums-web.index');
Route::get('/albums-web/{id}', [App\Http\Controllers\NewsController::class, 'show'])->name('albums-web.show');
Route::get('/contact', [App\Http\Controllers\ContactController::class, 'index'])->name('contact');
Route::get('/privacy-policy', [App\Http\Controllers\HomeController::class, 'privacyPolicy'])->name('privacy-policy');

Route::get('/register-verification', [App\Http\Controllers\AccountVerificationController::class,'registerVerification'])->name('register-verification.index');

Route::group(
    ['prefix' => 'portal'],
    function () {
        Route::get('dashboard', [App\Http\Controllers\DashboardController::class,'index'])->name('portal.index');
        Route::resource('profiling', App\Http\Controllers\StudentProfileController::class);

        Route::resource('account-verification', App\Http\Controllers\AccountVerificationController::class);

        Route::get('account-verification/{id}/verify/{status}', [App\Http\Controllers\AccountVerificationController::class, 'verifyModal'])->name('account-verification.verify-modal');

        Route::put('account-verification/{id}/verify/{status}', [App\Http\Controllers\AccountVerificationController::class, 'verify'])->name('account-verification.verify');

        Route::get(
            'student-profile-list',
            [App\Http\Controllers\StudentProfileController::class,
            'studentProfileDataTable']
        )->name('student-profile-list');

        Route::get(
            '/profiling/delete/{id}',
            [App\Http\Controllers\StudentProfileController::class,'delete']
        )->name('profiling.delete');

        Route::get(
            '/profiling/image/{file}',
            [App\Http\Controllers\StudentProfileController::class, 'getImage']
        )->name('profiling.image');

        Route::resource('visitor-log', App\Http\Controllers\VisitorLogController::class);

        Route::get(
            'visitor-log-list',
            [App\Http\Controllers\VisitorLogController::class,
            'visitorLogDatatable']
        )->name('visitor-log-list');

        Route::get(
            '/visitor-log/delete/{id}',
            [App\Http\Controllers\VisitorLogController::class,'delete']
        )->name('visitor-log.delete');

        Route::resource('file-doc', App\Http\Controllers\FileDocController::class);

        Route::get(
            'file-doc-list',
            [App\Http\Controllers\FileDocController::class,
            'fileDocDatatable']
        )->name('file-doc-list');

        Route::get(
            '/file-doc/delete/{id}',
            [App\Http\Controllers\FileDocController::class,'delete']
        )->name('file-doc.delete');

        Route::get(
            '/download-docs/{id}',
            [App\Http\Controllers\FileDocController::class, 'downloadDocs'],
        )->name('download.docs');

        Route::resource('seminar', App\Http\Controllers\SeminarController::class);

        Route::get(
            'seminar-list',
            [App\Http\Controllers\SeminarController::class,
            'seminarDatatable']
        )->name('seminar-list');

        Route::get(
            '/seminar/delete/{id}',
            [App\Http\Controllers\SeminarController::class,'delete']
        )->name('seminar.delete');

        Route::get(
            '/seminar/register/{id}',
            [App\Http\Controllers\SeminarController::class,'register']
        )->name('seminar.register');

        Route::post(
            '/seminar/join/{id}',
            [App\Http\Controllers\SeminarController::class,'join']
        )->name('seminar.join');

        Route::get(
            'seminar/{id}/attendance',
            [App\Http\Controllers\SeminarAttendanceController::class,'create']
        )->name('seminar.attendance.create');

        Route::post(
            'seminar/{id}/attendance/user',
            [App\Http\Controllers\SeminarAttendanceController::class,'attend']
        )->name('user.attend.seminar');

        Route::post(
            'seminar/{id}/attendance',
            [App\Http\Controllers\SeminarAttendanceController::class,'store']
        )->name('seminar.attendance.store');

        Route::resource('evaluation', App\Http\Controllers\StudentEvaluationController::class);

        Route::get(
            'seminar/{id}/evaluation',
            [App\Http\Controllers\StudentEvaluationController::class,'create']
        )->name('seminar.evaluation.create');

        Route::post(
            'seminar/{id}/evaluation',
            [App\Http\Controllers\StudentEvaluationController::class,'store']
        )->name('seminar.evaluation.store');

        Route::get(
            'evaluation-list',
            [App\Http\Controllers\StudentEvaluationController::class,
            'evaluationDatatable']
        )->name('evaluation-list');

        Route::resource('counseling', App\Http\Controllers\CounselingController::class);

        Route::get(
            'counseling-list',
            [App\Http\Controllers\CounselingController::class,
            'individualCounselingDatatable']
        )->name('counseling-list');

        Route::get(
            '/counseling/delete/{id}',
            [App\Http\Controllers\CounselingController::class,'delete']
        )->name('counseling.delete');

        Route::resource('mini-library', App\Http\Controllers\MiniLibraryController::class);

        Route::get(
            'mini-library-list',
            [App\Http\Controllers\MiniLibraryController::class,
            'miniLibraryDatatable']
        )->name('mini-library-list');

        Route::get(
            '/mini-library/delete/{id}',
            [App\Http\Controllers\MiniLibraryController::class,'delete']
        )->name('mini-library.delete');

        Route::post('mini-library/{id}/borrower', [App\Http\Controllers\MiniLibraryItemController::class,
        'store'])->name('borrower-book.store');

        Route::get('mini-library/{id}/borrower', [App\Http\Controllers\MiniLibraryItemController::class,
        'create'])->name('borrower-book.create');

        Route::get(
            'books-borrow-list',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'borroBooksDatatable']
        )->name('books-borrow-list');

        Route::get(
            'books/borrow/{id}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'show']
        )->name('books-borrow.show');

        Route::put(
            'books/borrow/{id}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'update']
        )->name('books-borrow.update');

        Route::get(
            'borrow/request/{id}/status/{status}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'statusUpdate']
        )->name('borrow.approval');

        Route::put(
            'borrow_book/{id}/status/{status}',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'borrowApproved']
        )->name('borrow_update.approval');

        Route::get(
            'borrow_book/{id}/return',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'returnBookView']
        )->name('borrow_update.return_view');

        Route::put(
            'borrow_book/{id}/return',
            [App\Http\Controllers\MiniLibraryItemController::class,
            'returnBook']
        )->name('borrow_update.return');

        Route::resource('albums', App\Http\Controllers\AlbumController::class);

        Route::get(
            'album-list',
            [App\Http\Controllers\AlbumController::class,
            'albumDatatable']
        )->name('album-list');

        Route::get(
            '/album/delete/{id}',
            [App\Http\Controllers\AlbumController::class,'delete']
        )->name('albums.delete');

        Route::post(
            'albums-items/{id}',
            [App\Http\Controllers\AlbumController::class,'addPhotoAlbum']
        )->name('album-items.store');

        Route::resource('general-settings', App\Http\Controllers\GeneralController::class);

        Route::resource('counseling-request', App\Http\Controllers\CounselingRequestController::class);

        Route::get(
            'counseling-request-list',
            [App\Http\Controllers\CounselingRequestController::class,
            'counselingRequestDatatable']
        )->name('counseling-request-list');

        Route::get(
            'request/{id}/status/{status}',
            [App\Http\Controllers\CounselingRequestController::class,
            'statusUpdate']
        )->name('request.approval');

        Route::put(
            'request/{id}/status/{status}',
            [App\Http\Controllers\CounselingRequestController::class,
            'updateCounseling']
        )->name('request.update');

        Route::put('notification/{id}', [App\Http\Controllers\NotificationController::class, 'markAsViewNotification'])->name('markAsView');

        Route::get(
            'notification/all',
            [App\Http\Controllers\NotificationController::class,
            'index']
        )->name('notifications.index');
    }
);

resources/views/portal/profiling/create.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div align='right' style="margin-bottom: 20px;">
                    <a href="{{ route('profiling.index') }}"><button type="button" class="btn btn-default"><i class="fas fa-chevron-left"></i> Back</button></a>
                </div>
                <h4 class="card-title">Create Student Profile</h4>
                <form method="POST" id ="student-create" action="{{ route('profiling.store') }}">
                @csrf
                <div class="errors"></div>
                <p class="card-description">
                    Personal info
                </p>
                <div class="col-md-4" align="center">
                    <div class="profile-img">
                        <img  src="{{asset('web-design/img/default.png')}}" alt="" id="im" name="im"/>
                        <div class="file btn btn-lg btn-primary">
                            <span onclick="onImage()">Upload Photo</span>
                            <input type="file" onchange="onFileSelected(event)" name="image" id="image" accept="image/*" value="submit" style="display: none;" >
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">First Name</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="first_name" value="" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Middle Name</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="middle_name" value=""/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Last Name</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="last_name" value="" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Date of Birth</label>
                        <div class="col-sm-9">
                        <input type="date" class="form-control" style="border-left: solid 2.0px #ec0000" name="birth_date" value="" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Contact Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="contact_no" value="" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Section</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="section" value="" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Year</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="year" value="" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Gender</label>
                        <div class="col-sm-9">
                        <select class="form-control" name="gender" style="border-left: solid 2.0px #ec0000" data-validation="required">
                            <option value="">Select Gender</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="LGBTQ">LGBTQ</option>
                        </select>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Course</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="course" value="" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <!-- <div class="form-group row" style="margin-left:160px;">
                        <input class="form-check-input " type="checkbox" value="1" name="is_lgbt" id="" >
                        <label class="form-check-label" >
                            Are you a member of LGBT Community?
                        </label>
                    </div> -->
                    </div>
                </div>
                <div align="right" style="margin-bottom: 20px;">
                        <button type="submit" id="submit_product" class="btn btn-primary"><i class="fa fa-save" ></i> Submit</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $('#student-create').register_fields('.errors');
    function onImage() {
        $('#image').click();
    }

    function onFileSelected() {
        var selectedFile = event.target.files[0];
        var files = event.target.files;
        var reader = new FileReader();
        if(selectedFile && selectedFile.size < 2097152)
        {
            var imgtag = document.getElementById("im");
            imgtag.title = selectedFile.name;
            reader.onload = function(event) {
                imgtag.src = event.target.result;
            };
            reader.readAsDataURL(selectedFile);
        }
    }
</script>
@endpush
<style>
    .profile-img{
        text-align: center;
    }
    .profile-img img{
        width: 50%;
        height: 100%;
    }
    .profile-img .file {
        position: relative;
        overflow: hidden;
        margin-top: -20%;
        width: 50%;
        border: none;
        border-radius: 0;
        font-size: 15px;
        background: #212529b8;
    }
    .profile-img .file input {
        position: absolute;
        opacity: 0;
        right: 0;
        top: 0;
    }
</style>
@endsection

resources/views/portal/profiling/delete.blade.php
<form method="POST" id="remove_bhw_form"  class="form-horizontal" action="{{route('profiling.destroy',$profiling->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{$profiling->first_name}}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{ route('profiling.show', $profiling->id) }}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/portal/profiling/edit.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div align='right' style="margin-bottom: 20px;">
                    <a href="{{ route('profiling.index') }}"><button type="button" class="btn btn-default"><i class="fas fa-chevron-left"></i> Back</button></a>
                </div>
                <h4 class="card-title">Edit Student Profile</h4>
                <form method="POST" id ="student-create" action="{{ route('profiling.update', $profiling->id) }}">
                    <input type="hidden" name="_method" value="PUT">
                @csrf
                <div class="errors"></div>
                <p class="card-description">
                    Personal info
                </p>
                <div class="col-md-4" align="center">
                    <div class="profile-img">
                        <img  src="{{ $profiling->image == null ? asset('web-design/images/default.png') : route('profiling.image', $profiling->image) }}" alt="" id="im" name="im"/>
                        <div class="file btn btn-lg btn-primary">
                            <span onclick="onImage()">Change Photo</span>
                            <input type="file" onchange="onFileSelected(event)" name="image" id="image" accept="image/*" value="submit" style="display: none;" >
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">First Name</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="first_name" value="{{ $profiling->first_name }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Middle Name</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" name="middle_name" value="{{ $profiling->middle_name }}"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Last Name</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="last_name" value="{{ $profiling->last_name }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Date of Birth</label>
                        <div class="col-sm-9">
                        <input type="date" class="form-control" style="border-left: solid 2.0px #ec0000" name="birth_date" value="{{ $profiling->birth_date }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Contact Number</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="contact_no" value="{{ $profiling->contact_no }}" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Section</label>
                        <div class="col-sm-9">
                        <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="section" value="{{ $profiling->section }}" data-validation="required"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Year</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="year" value="{{ $profiling->year }}" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Gender</label>
                        <div class="col-sm-9">
                        <select class="form-control" name="gender" style="border-left: solid 2.0px #ec0000" data-validation="required">
                            <option value="Male" {{ $profiling->gender == 'Male' ? 'selected' : '' }}>Male</option>
                            <option value="Female" {{ $profiling->gender == 'Female' ? 'selected' : '' }}>Female</option>
                            <option value="LGBTQ" {{ $profiling->gender == 'LGBTQ' ? 'selected' : '' }}>LGBTQ</option>
                        </select>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">Course</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="course" value="{{ $profiling->course }}" />
                        </div>
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group row">
                        <label class="col-sm-3 col-form-label">StudentID</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" style="border-left: solid 2.0px #ec0000" name="student_id   " value="{{ $profiling->student_id }}" data-validation="required" />
                        </div>
                    </div>
                    </div>
                </div>
                <div align="right" style="margin-bottom: 20px;">
                        <button type="submit" id="submit_product" class="btn btn-primary"><i class="fa fa-save" ></i> Submit</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $('#student-create').register_fields('.errors');
    function onImage() {
        $('#image').click();
    }

    function onFileSelected() {
        var selectedFile = event.target.files[0];
        var files = event.target.files;
        var reader = new FileReader();
        if(selectedFile && selectedFile.size < 2097152)
        {
            var imgtag = document.getElementById("im");
            imgtag.title = selectedFile.name;
            reader.onload = function(event) {
                imgtag.src = event.target.result;
            };
            reader.readAsDataURL(selectedFile);
        }
    }
</script>
@endpush
<style>
    .profile-img{
        text-align: center;
    }
    .profile-img img{
        width: 50%;
        height: 100%;
    }
    .profile-img .file {
        position: relative;
        overflow: hidden;
        margin-top: -20%;
        width: 50%;
        border: none;
        border-radius: 0;
        font-size: 15px;
        background: #212529b8;
    }
    .profile-img .file input {
        position: absolute;
        opacity: 0;
        right: 0;
        top: 0;
    }
</style>
@endsection

resources/views/portal/profiling/index.blade.php
@extends('portal.layouts.app')

@section('content')
<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
            <div class="card-body">
                    <div align='right'>
                        <a href="{{ route('profiling.create') }}"><button type="button" class="btn btn-primary"><i class="fas fa-plus"></i> New</button></a>
                    </div>
                <h4 class="card-title">Profiling</h4>
                <p class="card-description">
                </p>
                <div class="table-responsive">
                <table class="table table-striped" id="student-table">
                    <thead>
                        <tr>
                            <th scope="col" width="10%">Image</th>
                            <th scope="col" width="20%">Name</th>
                            <th scope="col" width="17%">StudentId</th>
                            <th scope="col" width="15%">Gender</th>
                            <th scope="col" width="15%">User Type</th>
                            <th scope="col" width="15%">Contact No.</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
<script>
    $(function() {
        $('#student-table').DataTable(
            {
                responsive: true,
                pagingType: "full_numbers",
                processing: true,
                serverSide: true,
                type: "GET",
                ajax:"{!! route('student-profile-list') !!}",
                columns:[
                    {data: "image","name":"image",orderable:false,searchable:false,"width":"10%", className:"v-align text-center",
                    "render": function (data) {
                        return "<center><div><img src='" + data + "' alt='Image' height='50' width='50' class='rounded-circle'></div></center>"; 
                    }},
                    {data: "full_name","name":"full_name","width":"30%",
                            "render": function (data, type, row, meta) {
                                var url = '{{ route("profiling.show", ":id") }}';
                                url = url.replace(':id', row.id);
                                return "<a href='"+url+"'>"+data+"</a>"; 
                    }},
                    {data: "student_id", 'name' :"student_id",orderable:false,searchable:false,"width":"22%",
                    "render": function (data) {
                        return "<span class='badge badge-pill badge-secondary'>"+data+"</span>"; 
                    }},
                    {data: "gender","name":"gender","width":"20%"},
                    {data: "section", 'name' :"section",orderable:false,searchable:false,"width":"15%"},
                    {data: "contact_no", 'name' :"contact_no",orderable:false,searchable:false,"width":"15%"}
                ]
            }
        );
    });
</script>
@endpush
@endsection